import { Users, ShoppingCart, Folder, PieChart } from "lucide-react";

export const Statistics = [
  {
    id: 1,
    title: "Total Users",
    value: "2,543",
    change: "+12.5%",
    isPositive: true,
    timeframe: "from last month",
    icon: Users,
    color: "bg-purple-600",
    strokeColor: "#c084fc",
    gradientId: "purpleGradient",
    sparkData: [{ v: 10 }, { v: 25 }, { v: 15 }, { v: 45 }, { v: 30 }, { v: 60 }],
  },
  {
    id: 2,
    title: "Total Sales",
    value: "$23,894",
    change: "+8.2%",
    isPositive: true,
    timeframe: "from last month",
    icon: ShoppingCart,
    color: "bg-blue-500",
    strokeColor: "#60a5fa",
    gradientId: "blueGradient",
    sparkData: [{ v: 20 }, { v: 10 }, { v: 35 }, { v: 25 }, { v: 50 }, { v: 40 }],
  },
  {
    id: 3,
    title: "Total Tasks",
    value: "1,423",
    change: "-4.3%",
    isPositive: false,
    timeframe: "from last month",
    icon: Folder,
    color: "bg-emerald-500",
    strokeColor: "#4ade80",
    gradientId: "greenGradient",
    sparkData: [{ v: 15 }, { v: 30 }, { v: 20 }, { v: 40 }, { v: 35 }, { v: 55 }],
  },
  {
    id: 4,
    title: "Total Projects",
    value: "32",
    change: "+6.7%",
    isPositive: true,
    timeframe: "from last month",
    icon: PieChart,
    color: "bg-orange-500",
    strokeColor: "#fb923c",
    gradientId: "orangeGradient",
    sparkData: [{ v: 10 }, { v: 20 }, { v: 15 }, { v: 35 }, { v: 25 }, { v: 10 }],
  },
];